---
- name: Install nginix
  hosts: all
  become: true

  tasks:
    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest

    - name: Start NGiNX
      service:
        name: nginx
        state: started
      notify: Restart Nginx
    - name: Nginx status
      ansible.builtin.debug:
        msg:
         - "nginx started successfully"
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
